# Default initial position for each movable joint
initial_positions:
  link1_to_link2: 0.15
  link2_to_link3: -0.45
  link3_to_link4: 0.65
  link4_to_link5: -0.25
  link5_to_link6: 0.20
  link6_to_link6_flange: 0.0
  gripper_controller: 0.0
